micronaut:
  application:
    name: tigal
datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/xe
    driverClassName: oracle.jdbc.OracleDriver
    username: system
    password: oracle
kafka.bootstrap.servers: localhost:9092
